/*
 * This file was automatically generated by EvoSuite
 * Thu May 02 15:18:46 GMT 2024
 */

package com.myapplication.projetopoo2324;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.myapplication.projetopoo2324.Estado;
import com.myapplication.projetopoo2324.GymApplication;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class GymApplication_ESTest extends GymApplication_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      GymApplication gymApplication0 = new GymApplication();
      // Undeclared exception!
      try { 
        gymApplication0.init((Estado) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.myapplication.projetopoo2324.GymApplication", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("init.txt");
      FileSystemHandling.createFolder(evoSuiteFile0);
      GymApplication gymApplication0 = new GymApplication();
      Estado estado0 = new Estado();
      gymApplication0.init(estado0);
      assertEquals(1, estado0.getNewUserCode());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      GymApplication gymApplication0 = new GymApplication();
      Estado estado0 = new Estado();
      gymApplication0.init(estado0);
      gymApplication0.init(estado0);
      assertEquals(3, estado0.getNewUserCode());
  }
}
